name: hisabbox
description: An offline-first SMS parser that tracks bKash, Nagad, and Rocket wallet messages
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  material_color_utilities: ^0.11.1
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.7.2
  
  # Local Storage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  
  # SMS Reading
  another_telephony: ^0.4.1
  
  # HTTP for webhook
  dio: ^5.9.0
  
  # Permissions
  permission_handler: ^12.0.1

  # Background Processing
  workmanager: ^0.9.0+3

  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # JSON
  json_annotation: ^4.9.0
  
  # Utilities
  intl: ^0.20.2
  crypto: ^3.0.6
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  sqflite_common_ffi: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/hisabbox.png"
  adaptive_icon_background: "#00695C"
  adaptive_icon_foreground: "assets/icon/hisabbox.png"
