name: Android Split APK Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from pubspec
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | head -n1 | cut -d' ' -f2)
          version_no_build=${version%%+*}
          echo "version=$version_no_build" >> "$GITHUB_OUTPUT"
          echo "Detected pubspec version: $version_no_build"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build split APKs
        run: flutter build apk --release --split-per-abi

      - name: Collect release artifacts
        run: |
          mkdir -p release
          cp build/app/outputs/flutter-apk/app-*-release.apk release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: HisabBox v${{ steps.version.outputs.version }}
          body: |
            Automated release for version ${{ steps.version.outputs.version }} generated from tag ${{ github.ref_name }}.
          files: release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
